// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceptbokApi.Data;

#nullable disable

namespace ReceptbokApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927134020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ReceptbokApi.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pannkakor är som allra godast när de är tunna och frasiga. Här har du ett recept på pannkakor där du får precis det. Sätt guldkant på dagen med nygräddade pannkakor. Servera tillsammans med något sött eller salt.",
                            Image = "https://images.unsplash.com/photo-1587339144367-f1cacbecac82?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Title = "Pannkakor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Köttbullar med gräddsås och kokt potatis är en klassisk husmansrätt som är populär hos hela familjen, alltid ett säkert kort! Servera med pressgurka och lingon.",
                            Image = "https://images.unsplash.com/photo-1600688685721-852c38f6e8a6?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Title = "Köttbullar med gräddsås, lingon och pressgurka"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Laxfilé i ugn med kokt potatis och en enkel romsås. Detta är världens godaste lax, både enligt vuxna och barn. Enkel och så uppskattad rätt!",
                            Image = "https://images.unsplash.com/photo-1560717845-968823efbee1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Title = "Lax i ugn"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hemgjord pizzadeg med torrjäst eller färsk jäst, vatten och mjöl. Enkelt och så gott att toppa med det du gillar bäst!",
                            Image = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Title = "Pizza"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Carnitas är mexikanska tacos där långbakad fläskkarré i ugn blir så mört så att det faller isär – perfekt för att äta tacos som i Mexiko. Servera hemgjord Crema Mexicana (syrad grädde) och andra goda tillbehör till carnitas för en autentisk och festlig tacoupplevelse.",
                            Image = "https://plus.unsplash.com/premium_photo-1661730329741-b3bf77019b39?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Title = "Carnitas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
